default:
  tags:
    - maven
    - jdk8

stages:
    - build
    - deploy

compile:
    stage: build
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    script:
        - echo "Building Using Maven.."
        - rm -rf ./target/cns-authenticator.jar
        - mvn clean package
    artifacts:
        name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_JOB_STAGE}_${CI_COMMIT_SHA}"
        expire_in: 1 week # save gitlab server space, we copy the files we need to deploy folder later on
        paths: 
            - './target' # our artifacts folder

deploy_production:
    stage: deploy
    script:
        - echo "Deploy to Production Server.."
        - export SSHPASS=$DEPLOY_PWD_PROD
        - echo "Edit Permissions.."
#        - sshpass -e ssh -o stricthostkeychecking=no gitlabdeploy.prod@10.184.250.10 "sudo chown -R gitlabdeploy.prod:gitlabdeploy.prod /opt/keycloak_spid/standalone/deployments"
#        - echo "Clear old files.."
#        - sshpass -e ssh -o stricthostkeychecking=no gitlabdeploy.prod@10.184.250.10 "rm -rf /opt/keycloak_spid/standalone/deployments/mise-keycloak-themes.jar"
        - echo "Copying files..."
        - sshpass -e scp -o stricthostkeychecking=no -rp ./target/cns-authenticator.jar gitlabdeploy.prod@10.184.250.10:/home/gitlabdeploy.prod/
        - echo "Installing files.."
        - sshpass -e ssh -o stricthostkeychecking=no gitlabdeploy.prod@10.184.250.10 "sudo install -C -o wildfly -g wildfly /home/gitlabdeploy.prod/cns-authenticator.jar /opt/keycloak_spid/standalone/deployments/"
        - echo "Done!"

    environment:
        name: production
    when: manual
    only:
        - tags
